version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - SESSION_SECRET=${SESSION_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - BASE_URL=${BASE_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - FACEBOOK_APP_ID=${FACEBOOK_APP_ID}
      - FACEBOOK_APP_SECRET=${FACEBOOK_APP_SECRET}
      - TWITTER_API_KEY=${TWITTER_API_KEY}
      - TWITTER_API_SECRET=${TWITTER_API_SECRET}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
      - FACEBOOK_CALLBACK_URL=${FACEBOOK_CALLBACK_URL}
      - TWITTER_CALLBACK_URL=${TWITTER_CALLBACK_URL}
    volumes:
      - ./:/app
    restart: unless-stopped
    # Note: health check for AWS Cloud DynamoDB
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').request({host: 'dynamodb.${AWS_REGION}.amazonaws.com', port: 443, path: '/'}, (res) => process.exit(res.statusCode === 200 ? 0 : 1)).end()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s